#!/usr/bin/env bash

docker build --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
             --build-arg SOURCE_COMMIT=${SOURCE_COMMIT:0:7} \
             --build-arg SOURCE_URL=$(git config --get remote.origin.url) \
             --build-arg IMAGE_NAME=${IMAGE_NAME} \
             -t $IMAGE_NAME .